import { ContentTypeValues } from "@ahoo-wang/fetcher";
import { type ApiMetadata, type ApiMetadataCapable, api, attribute, autoGeneratedError, del, path, post, put, request } from "@ahoo-wang/fetcher-decorator";
import { JsonEventStreamResultExtractor } from "@ahoo-wang/fetcher-eventstream";
import type { CommandBody, CommandRequest, CommandResult, CommandResultEventStream, DeleteAggregateCommand, RecoverAggregateCommand } from "@ahoo-wang/fetcher-wow";
import type { CreateView, EditView } from "./types";
import { VIEWER_BOUNDED_CONTEXT_ALIAS } from "../boundedContext";

export enum ViewCommandEndpointPaths {
    CREATE_VIEW = '/tenant/{tenantId}/owner/{ownerId}/view/type/{type}',
    DEFAULT_DELETE_AGGREGATE = '/tenant/{tenantId}/owner/{ownerId}/view/{id}',
    DEFAULT_RECOVER_AGGREGATE = '/tenant/{tenantId}/owner/{ownerId}/view/{id}/recover',
    EDIT_VIEW = '/tenant/{tenantId}/owner/{ownerId}/view/{id}/type/{type}'
}

export type CreateViewCommand = CommandBody<CreateView>;
export type EditViewCommand = CommandBody<EditView>;

const DEFAULT_COMMAND_CLIENT_OPTIONS: ApiMetadata = {
    basePath: VIEWER_BOUNDED_CONTEXT_ALIAS
};

@api()
export class ViewCommandClient<R = CommandResult> implements ApiMetadataCapable {
    constructor(public readonly apiMetadata: ApiMetadata = DEFAULT_COMMAND_CLIENT_OPTIONS) {
    }

    /**
     * 创建视图
     * - operationId: `viewer.view.create_view`
     * - path: `/tenant/{tenantId}/owner/{ownerId}/view/type/{type}`
     */
    @post(ViewCommandEndpointPaths.CREATE_VIEW)
    createView(@path('type') type: string, @request() commandRequest: CommandRequest<CreateViewCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(type, commandRequest, attributes);
    }

    /**
     * Delete aggregate
     * - operationId: `viewer.view.default_delete_aggregate`
     * - path: `/tenant/{tenantId}/owner/{ownerId}/view/{id}`
     */
    @del(ViewCommandEndpointPaths.DEFAULT_DELETE_AGGREGATE)
    defaultDeleteAggregate(@path('id') id: string, @request() commandRequest?: CommandRequest<DeleteAggregateCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(id, commandRequest, attributes);
    }

    /**
     * Recover deleted aggregate
     * - operationId: `viewer.view.default_recover_aggregate`
     * - path: `/tenant/{tenantId}/owner/{ownerId}/view/{id}/recover`
     */
    @put(ViewCommandEndpointPaths.DEFAULT_RECOVER_AGGREGATE)
    defaultRecoverAggregate(@path('id') id: string, @request() commandRequest?: CommandRequest<RecoverAggregateCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(id, commandRequest, attributes);
    }

    /**
     * 修改视图
     * - operationId: `viewer.view.edit_view`
     * - path: `/tenant/{tenantId}/owner/{ownerId}/view/{id}/type/{type}`
     */
    @put(ViewCommandEndpointPaths.EDIT_VIEW)
    editView(@path('type') type: string, @path('id') id: string, @request() commandRequest: CommandRequest<EditViewCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(type, id, commandRequest, attributes);
    }
}

@api('', {
    headers: { Accept: ContentTypeValues.TEXT_EVENT_STREAM },
    resultExtractor: JsonEventStreamResultExtractor,
})
export class ViewStreamCommandClient extends ViewCommandClient<CommandResultEventStream> {
    constructor(apiMetadata: ApiMetadata = DEFAULT_COMMAND_CLIENT_OPTIONS) {
        super(apiMetadata);
    }
}
